url: https://office206.github.io
baseurl: /hoofarp/

# Site settings
title: Lotus Industries and Consulting Group
email: hp@lotustech.io
description: "Lotus Industries and Consulting Group Project page and main page. We focus on Data Engineering, Data Visuallization in eCommerce (Shipify and bigcommerce)."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/hoofarpourzand
  - title: github
    url: http://github.com/office206
   
